config/routes.rb
Rails.application.routes.draw do
  root 'procedures#index'

  get 'users/sign_up' => 'procedures#notfound'
  devise_for :users
  get 'procedures/finished' => 'procedures#finished'
  get 'procedures/:id/finish_procedure' => 'procedures#finish_procedure', as: :finish_procedure
  get 'procedures/:id/reports' => 'procedures#reports', as: :procedure_reports
  post 'procedures/:id/avatar' => 'procedures#avatar', as: :procedure_avatar
  post 'procedures/:id/image' => 'procedures#image', as: :procedure_image
  delete 'procedures/:id/image/:category/:image_id' => 'procedures#purge_image', as: :purge_image
  get 'procedures/:id/print' => 'procedures#print'
  resources :procedures, only:[:new, :create, :edit, :update, :destroy, :show] do
  	resources :works, only:[:new, :create, :edit, :update, :destroy, :show]
  end
  resources :recipes, only:[:index, :new, :create, :edit, :update, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/procedure.rb
class Procedure < ApplicationRecord
	has_one_attached :avatar, dependent: :destroy
	has_many_attached :photos, dependent: :destroy
	has_many_attached :raysx, dependent: :destroy
	has_many_attached :teleraysx, dependent: :destroy
	has_many_attached :traceds, dependent: :destroy
	has_many_attached :usps, dependent: :destroy
	has_many_attached :reports, dependent: :destroy
	has_many :works, dependent: :destroy

	def thumbnail
		return self.photos.variant(resize: '300x300')
	end
end

app/models/recipe.rb
class Recipe < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :procedure
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/procedures_controller.rb
class ProceduresController < ApplicationController
	before_action :authenticate_user!, only:[:index, :create, :reports, :avatar, :image, :purge_image,]
	def index
		@title = 'PROCESSOS ABERTOS'
		@procedures = Procedure.where(status: false)
	end

	def finished
		@title = 'PROCESSOS CONCLUÍDOS'
		@procedures = Procedure.where(status: true)
		render :index
	end

	def new
		@procedure = Procedure.new
	end

	def create
		values = params.require(:procedure).permit!
		@procedure = Procedure.create values
		if @procedure.save
			@procedure.update(status: false)
			redirect_to procedure_path(@procedure), notice: 'Processo Registrado!'
		else
			render :new
		end
	end

	def edit
		@procedure = Procedure.find(params[:id])
	end

	def update
		@procedure = Procedure.find(params[:id])
		values = params.require(:procedure).permit!
		@procedure.update values
		redirect_to procedure_path(@procedure), notice: 'Processo Atualizado!'
	end

	def finish_procedure
		@procedure = Procedure.find(params[:id])
		@procedure.update(status: true)
		redirect_to procedure_path(@procedure), notice: 'Processo finalizado!'
	end

	def print
		@procedure = Procedure.find(params[:id])
		respond_to do |format|
			format.html
			format.json
			format.pdf { render template: 'procedures/print', pdf: 'print'}
		end
	end

	def show
		@procedure = Procedure.find(params[:id])

		procedure_items = [@procedure.item_1, @procedure.item_2, @procedure.item_3, 
		@procedure.item_4, @procedure.item_5, @procedure.item_6, @procedure.item_7,
		@procedure.item_8, @procedure.item_9, @procedure.item_10, @procedure.item_11,
		@procedure.item_12, @procedure.item_13, @procedure.item_14, @procedure.item_15,
		@procedure.item_16, @procedure.item_17, @procedure.item_18]

		@items = []
		procedure_items.each do |item|
			if item == 0
				@items <<  'NAO'
			else
				@items << 'SIM'
			end
		end
	end

	def avatar
		@procedure = Procedure.find(params[:id])
		@procedure.avatar.attach(params[:procedure][:avatar])
		redirect_to procedure_path(@procedure), notice: 'Imagem Adicionada!'
	end

	def image
		@procedure = Procedure.find(params[:id])
		image_category = params[:procedure][:category]
		if image_category == 'photos'
			@procedure.photos.attach(params[:procedure][:image])
		elsif image_category == 'raysx'
			@procedure.raysx.attach(params[:procedure][:image])
		elsif image_category == 'teleraysx'
			@procedure.teleraysx.attach(params[:procedure][:image])
		elsif image_category == 'traceds'
			@procedure.traceds.attach(params[:procedure][:image])
		elsif image_category == 'usps'
			@procedure.usps.attach(params[:procedure][:image])
		elsif image_category == 'reports'
			@procedure.reports.attach(params[:procedure][:image])
		end	
		
		redirect_to procedure_path(@procedure), notice: 'Imagem Adicionada!'
	end

	def purge_image
		@procedure = Procedure.find(params[:id])
		image_category = params[:category]
		if image_category == 'photos'
			@procedure.photos.find(params[:image_id]).purge
		elsif image_category == 'raysx'
			@procedure.raysx.find(params[:image_id]).purge
		elsif image_category == 'teleraysx'
			@procedure.teleraysx.find(params[:image_id]).purge
		elsif image_category == 'traceds'
			@procedure.traceds.find(params[:image_id]).purge
		elsif image_category == 'usps'
			@procedure.usps.find(params[:image_id]).purge
		elsif image_category == 'reports'
			@procedure.reports.find(params[:image_id]).purge
		end

		redirect_to procedure_path(@procedure), notice: 'Imagem Removida!'
	end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_recipe, only: [:edit, :update]

	def index
		@recipes = Recipe.order :date_recipe
		@recipes = @recipes.reverse
	end

	def new
		@recipe = Recipe.new
	end

	def create
		values = params.require(:recipe).permit!
		@recipe = Recipe.create values
		if @recipe.save
			redirect_to recipes_path, notice: 'Receita Salva!'
		else
			render :new
		end
	end

	def edit
	end

	def update
		values = params.require(:recipe).permit!
		@recipe.update values
		redirect_to recipes_path, notice: 'Receita Atualizada!'
	end
	
	def destroy
		id = params[:id]
		Recipe.destroy id
		redirect_to recipes_path, notice: 'Receita Excluída!'
	end

	private
		def set_recipe
			@recipe = Recipe.find(params[:id])
		end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController

	def new
		@procedure = Procedure.find(params[:procedure_id])
		@work = Work.new
	end

	def create
		@procedure = Procedure.find(params[:procedure_id])
		values = params.require(:work).permit!
		@work = Work.new values
		@work.procedure_id = params[:procedure_id]
		if @work.save
			redirect_to procedure_path(@procedure), notice: 'Procedimento Registrado'
		else
			render :new
		end
	end

	def edit
		@procedure = Procedure.find(params[:procedure_id])
		@work = Work.find(params[:id])
	end

	def update
		@procedure = Procedure.find(params[:procedure_id])
		@work = Work.find(params[:id])
		values = params.require(:work).permit!
		@work.update values

		redirect_to procedure_path(@procedure), notice: 'Procedimento Atualizado!'
	end

	def destroy
		@procedure = Procedure.find(params[:procedure_id])
		Work.destroy params[:id]
		redirect_to procedure_path(@procedure), notice: 'Procedimento Excluído!'
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def datebr(date)
		if date != nil
			date = date.strftime("%d/%m/%Y")
		end
	end

	def moneybr(money)
		if money != nil
		  money = number_to_currency money
		end
	end

	def wicked_image_active_storage_workaround( image )
	  if image.is_a? ActiveStorage::Attachment
	    save_path = Rails.root.join( "tmp", "#{image.id}.jpg")
	    File.open(save_path, 'wb') do |file|
	      file << image.blob.download
	    end
	    return save_path.to_s
	  end
	end
end

app/helpers/procedures_helper.rb
module ProceduresHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NewSmile</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class="top-bar">
        <div class="logo">
          <%= link_to (image_tag 'logo.jpg', :width=>'100px'), root_path %>
        </div>
        <div class="navbar">
          <div class="menu">
            <span><%= link_to 'Procedimentos Abertos', root_path %></span>
            <span><%= link_to 'Procedimentos Concluídos', procedures_finished_path %></span>
            <span><%= link_to 'Caixa', recipes_path %></span>
          </div>
          <% if signed_in? %>
            <p class="btn-exit" >
              <%= link_to destroy_user_session_path, method: :delete do %>
                <i class="fa fa-sign-out"></i>
              <% end %>
            </p>
          <% end %>
        </div>
      </div>
    </header>
    <div style="padding-top: 4em;">
      <div class="col-lg-12 col-md-12 com-sm-12">
        <% if flash[:notice] %>
          <div class="alert alert-info">
            <%= flash[:notice] %>
          </div>
        <% end %>
      </div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/procedures/show.html.erb
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="container">
			<h2 align="center"><b>PROCESSO Nº <%= @procedure.id %></b></h2><br><br>
			<div class="procedure-menu">
				<span id="personalInformations" class="tabs" onclick="activeTab('personalInformations')" >Dados Pessoais</span>
				<span id="works" class="tabs" onclick="activeTab('works')" >Trabalhos Realizados</span>
				<span id="photos" class="tabs" onclick="activeTab('photos')" >Fotografías</span>
				<span id="rayx" class="tabs" onclick="activeTab('rayx')" >Raio-X Panorâmico</span>
				<span id="telerayx" class="tabs" onclick="activeTab('telerayx')" >Teleradiografía</span>
				<span id="traced" class="tabs" onclick="activeTab('traced')" >Traçado Cefalometrico</span>
				<span id="usp" class="tabs" onclick="activeTab('usp')" >Fator USP</span>
				<span id="report" class="tabs" onclick="activeTab('report')" >Laudo Radiográfico</span>
				<%= link_to "#{@procedure.id}/print.pdf" do %>
					<i class="fa fa-print btn-print"></i>
				<% end %>
			</div>
			<div class="procedure-box">
				<div id="personalInformations-box" class="container-procedure no-active">
					<div class="avatar">
						<% if @procedure.avatar.attached? %>
							<%= link_to (image_tag @procedure.avatar.variant(resize: '250x300!').processed), url_for(@procedure.avatar) %>
							<% if signed_in? %>
								<%= form_with model: @procedure, url: procedure_avatar_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
									<p align="right"><%= f.file_field :avatar %></p>
									<p><%= f.submit :Enviar, class: 'btn btn-success' %></p>
								<% end %>
							<% end %>
						<% else %>
							<h3>Não há imagem</h3>
							<% if signed_in? %>
								<%= form_with model: @procedure, url: procedure_avatar_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
									<p align="right"><%= f.file_field :avatar %></p>
									<p><%= f.submit :Enviar, class: 'btn btn-success' %></p>
								<% end %>
							<% end %>
						<% end %>
					</div>
					<h4><b>* INFORMAÇOES DO PACIENTE</b>
						<span style="margin-left: 1em;" class="options">
							<%= link_to edit_procedure_path(@procedure) do %>
								<i class="fa fa-edit"></i>
							<% end %>
							<% if signed_in? %>
								<% if @procedure.status == false %>
									<%= link_to finish_procedure_path(@procedure), data:{confirm: 'Finalizar este procedimento?'} do %>
										<i class="fa fa-check"></i>
									<% end %>
								<% end %>
							<% end %>
							</span>
						
					</h4><br>
					<h3><b><%= @procedure.patient %></b></h3>
					<h3><b>DR. <%= @procedure.doctor %></b></h3>
					<h4><b>DATA: </b><%= datebr(@procedure.date_procedure) %>
					<span style="margin-left: 3em;"><b>SEXO: </b><%= @procedure.sex %></span>
					<span style="margin-left: 3em;"><b>CIDADE: </b><%= @procedure.city %></span> 
					</h4>
					<h4><b>OBS: </b><%= @procedure.note %></h4>
					<hr>

					<h4><b>* INFORMAÇOES ORTODONTICAS</b></h4><br>
					<h4><b>TRATAMENTO ORTODONTICO ANTERIOR: </b><%= @procedure.last_procedure %></h4>
					<h4><b>RAZOES PARA O TRATAMENTO ORTODONTICO: </b><%= @procedure.reason %></h4>
					<h4><b>GRAU DE MOTIVAÇAO: </b><%= @procedure.motivation %></h4><br>
					
					<h4 align="center"><b>HISTORICO MEDICO</b></h4><br>
					<h4><b>O PACIENTE JA APRESENTOU</b></h4>
					<hr>
					<div class="form-group col-lg-4 col-md-4">
						<h4><b>Asma: </b><%= @items[0] %></h4>
						<h4><b>Anemia: </b><%= @items[1] %></h4>
						<h4><b>Alergia: </b><%= @items[2] %></h4>
						<h4><b>Doença Sanguinea: </b><%= @items[3] %></h4>
						<h4><b>Doença Óssea: </b><%= @items[4] %></h4>
						<h4><b>Diabetes: </b><%= @items[5] %></h4>
					</div>
					<div class="form-group col-lg-4 col-md-4">
						<h4><b>Eplepsia: </b><%= @items[6] %></h4>
						<h4><b>Problemas Emocionais: </b><%= @items[7] %></h4>
						<h4><b>Problemas Endócrinos: </b><%= @items[8] %></h4>
						<h4><b>Doenças Cardíacas: </b><%= @items[9] %></h4>
						<h4><b>Disturbios Auditivos: </b><%= @items[10] %></h4>
						<h4><b>Disturbios Respiratórios: </b><%= @items[11] %></h4>
					</div>
					<div class="form-group col-lg-4 col-md-4" style="margin-bottom: 3em;">
						<h4><b>Traumatísmo de Face/Cabeça: </b><%= @items[12] %></h4>
						<h4><b>Herpes: </b><%= @items[13] %></h4>
						<h4><b>Hepatite: </b><%= @items[14] %></h4>
						<h4><b>Febre Reumática: </b><%= @items[15] %></h4>
						<h4><b>Fraturas Ósseas: </b><%= @items[16] %></h4>
						<h4><b>Outros: </b><%= @items[16] %></h4>
					</div>
					<h4><b>INGERE DROGAS OU MEDICAMENTOS: </b><%= @procedure.drugs %>
					<span style="margin-left: 6em;"><b>ANTICONCEPCIONAL: </b><%= @procedure.contraceptive %></span></h4>
					<h4><b>ANOMALIASCONGENITAS: </b><%= @procedure.anomaly %></h4>
					<h4><b>ESTAGIO DE DESENVOLVIMENTO OSSEO: </b><%= @procedure.bone_development %>
					<span style="margin-left: 6em"><b>TIPO FISICO: </b><%= @procedure.physical_type %></span>
					<span style="margin-left: 3em;"><b>ALTURA: </b><%= @procedure.height %></span>
					<span style="margin-left: 3em;"><b>PESO: </b><%= @procedure.weight %></span></h4>
					<h4><b>CIRURGIA ANTERIOR: </b><%= @procedure.last_surgery %>
					<span style="margin-left: 6em;"><b>SAUDE ATUAL: </b><%= @cheers %></span>
					</h4>
				</div>
				<div id="works-box" class="container-procedure no-active">
					<h4 align="center"><b>PROCEDIMENTOS REALIZADOS</b></h4><br>
					<p><%= link_to 'Registrar Novo Procedimento', new_procedure_work_path(@procedure), class: 'btn btn-success' %></p>
					<table class="table table-bordered">
						<thead>
							<th>Data</th>
							<th>Procedimento Realizado no Paciente</th>
							<th>Procedimento Futuro</th>
						</thead>
						<tbody>
							<% @procedure.works.each do |work| %>
							<tr>
								<td><%= datebr(work.date_work) %></td>
								<td><%= work.description %></td>
								<td><%= work.next_work %></td>
								<% if signed_in? %>
								<td class="options">
									<%= link_to edit_procedure_work_path(@procedure, work) do %>
										<i class="fa fa-edit"></i>
									<% end %>
									<%= link_to procedure_work_path(@procedure, work), method: :delete, data:{confirm: 'Excluir este trabalho?'} do %>
										<i class="fa fa-trash"></i>
									<% end %>
								</td>
								<% end %>
							</tr>
							<% end %>
						</tbody>
					</table>
				</div>
				<div id="photos-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'photos' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.photos.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'photos', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
				<div id="rayx-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'raysx' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.raysx.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'raysx', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
				<div id="telerayx-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'teleraysx' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.teleraysx.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'teleraysx', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
				<div id="traced-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'traceds' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.traceds.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'traceds', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
				<div id="usp-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'usps' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.usps.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'usps', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
				<div id="report-box" class="container-procedure no-active">
					<div class="col-lg-12 col-md-12 col-sm-12">
						<% if signed_in? %>
							<%= form_with model: @procedure, url: procedure_image_path(@procedure), method: :post, id: 'procedures', local: true do |f| %>
								<div class="add-photos">
									<%= f.hidden_field :category, value: 'reports' %>
									<p><b>Adicionar Nova Imagem</b></p>
									<span><%= f.file_field :image %></span> 
									<span style="margin-left: -3em"><%= f.submit :Enviar,class: 'btn btn-success' %></span>
								</div>
							<% end %>
						<% end %>
					</div>
					<% @procedure.reports.each do |photo| %>
					<div class="col-lg-3 col-md-3 col-sm-12 photo">
						<%= link_to (image_tag photo.variant(resize: '250x250!').processed), url_for(photo) %>
						<% if signed_in? %>
							<%= link_to purge_image_path(@procedure, 'reports', photo ), method: :delete, data:{confirm: 'Remover esta imagem?'} do %>
								<i class="fa fa-trash btn-delete"></i>
							<% end %>
						<% end %>
					</div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
	initial();
</script>

app/views/recipes/index.html.erb
<div class="row">
	<div class="col-lg-12 col-md-12 col-sm-12">
		<div class="container-big">
			<h2 align="center"><b>RECEITAS DE CAIXA</b></h2><br>
			<p style="float: left;"><%= link_to 'Nova Receita', new_recipe_path, class: 'btn btn-success' %></p>
			<input type="text" id="search" placeholder="Buscar Recita" style="float: right; margin-bottom: 1em;">
			<table class="table table-bordered">
				<thead>
					<th>Data</th>
					<th>Nome</th>
					<th>Descrição</th>
					<th>Valor</th>
					<th></th>
				</thead>
				<tbody id="table">
					<% @recipes.each do |recipe| %>
					<tr>
						<td><%= datebr recipe.date_recipe %></td>
						<td><%= recipe.name %></td>
						<td><%= recipe.description %></td>
						<td><%= moneybr recipe.price %></td>
						<td class="options">
							<%= link_to edit_recipe_path(recipe) do %>
								<i class="fa fa-edit"></i>
							<% end %>
							<%= link_to recipe_path(recipe), method: :delete, data:{confirm: 'Excluir essa receita?'} do %>
								<i class="fa fa-trash"></i>
							<% end %>
						</td>
					</tr>
					<% end %>
				</tbody>
			</table>
		</div>
	</div>
</div>

<script type="text/javascript">
	$(function(){
	    $("#search").keyup(function(){
	        var texto = $(this).val();
	        $("#table tr").css("display", "table-row");
	        $("#table tr").each(function(){
	            if($(this).text().toUpperCase().indexOf(texto.toUpperCase()) < 0)
   				   $(this).css("display", "none");
	        });
	    });
	});
</script>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>